In [1]:
import pandas as pd
import datetime

In [2]:
def Average(lst): 
    return sum(lst) / len(lst)

In [3]:
perfdf = pd.read_csv("weatheradd.csv")

In [4]:
perfdf = perfdf.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)

In [5]:
perfdf['Date']= pd.to_datetime(perfdf['Date'])

In [6]:
perfdf.sort_values(by = ['Player', 'Date'])

,Date,Year,Player,Tm,p_Cmp,p_Att,p_Yds,p_TD,Int,Sk,...,re_Yds,re_TD,re_Lng,fmb,fmb_loss,stadium,home_away,win,temp,wind
109802,1995-11-27,1995,'Omar Ellison,San Diego Chargers,0.0,0.0,0.0,0.0,0.0,NaN,...,6.0,0.0,6.0,NaN,NaN,Qualcomm Stadium,home,1,61.0,6.0
112421,1996-09-29,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,Qualcomm Stadium,home,1,66.0,8.0
112609,1996-10-06,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,Mile High Stadium,away,0,60.0,9.0
113230,1996-10-21,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,Qualcomm Stadium,home,0,66.0,7.0
113449,1996-10-27,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,Seattle Kingdome,away,0,72.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207585,2015-01-18,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,Gillette Stadium,away,0,51.0,15.0
208866,2015-10-08,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,Reliant Stadium,away,1,76.0,2.0
211319,2015-12-06,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,0.0,7.0,0.0,0.0,Heinz Field,away,0,35.0,2.0
211617,2015-12-13,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,50.0,0.0,27.0,0.0,0.0,EverBank Field,away,0,77.0,8.0
211823,2015-12-20,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,Lucas Oil Stadium,home,0,72.0,0.0

In [7]:
perfdf.shape

(236719, 29)

In [8]:
headers = list(perfdf.columns.values)

In [ ]:
for d in headers:
    print(f"avg_{d}")

In [10]:
perfdf['avg_p_Cmp'] = ''
perfdf['avg_p_Att'] = ''
perfdf['avg_p_Yds'] = ''
perfdf['avg_p_TD'] = ''
perfdf['avg_Int'] = ''
perfdf['avg_Sk'] = ''
perfdf['avg_Yds_lost'] = ''
perfdf['avg_p_Lng'] = ''
perfdf['avg_p_Rate'] = ''
perfdf['avg_ru_Att'] = ''
perfdf['avg_ru_Yds'] = ''
perfdf['avg_ru_TD'] = ''
perfdf['avg_ru_Lng'] = ''
perfdf['avg_re_targ'] = ''
perfdf['avg_Rec'] = ''
perfdf['avg_re_Yds'] = ''
perfdf['avg_re_TD'] = ''
perfdf['avg_re_Lng'] = ''
perfdf['avg_fmb'] = ''
perfdf['avg_fmb_loss'] = ''

perfdf['last_p_Cmp'] = ''
perfdf['last_p_Att'] = ''
perfdf['last_p_Yds'] = ''
perfdf['last_p_TD'] = ''
perfdf['last_Int'] = ''
perfdf['last_Sk'] = ''
perfdf['last_Yds_lost'] = ''
perfdf['last_p_Lng'] = ''
perfdf['last_p_Rate'] = ''
perfdf['last_ru_Att'] = ''
perfdf['last_ru_Yds'] = ''
perfdf['last_ru_TD'] = ''
perfdf['last_ru_Lng'] = ''
perfdf['last_re_targ'] = ''
perfdf['last_Rec'] = ''
perfdf['last_re_Yds'] = ''
perfdf['last_re_TD'] = ''
perfdf['last_re_Lng'] = ''
perfdf['last_fmb'] = ''
perfdf['last_fmb_loss'] = ''

In [11]:
testdf = perfdf
testdf = testdf.sort_values(by = ['Player', 'Date'])

In [12]:
testdf

,Date,Year,Player,Tm,p_Cmp,p_Att,p_Yds,p_TD,Int,Sk,...,last_ru_Yds,last_ru_TD,last_ru_Lng,last_re_targ,last_Rec,last_re_Yds,last_re_TD,last_re_Lng,last_fmb,last_fmb_loss
109802,1995-11-27,1995,'Omar Ellison,San Diego Chargers,0.0,0.0,0.0,0.0,0.0,NaN,...,,,,,,,,,,
112421,1996-09-29,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,
112609,1996-10-06,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,
113230,1996-10-21,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,
113449,1996-10-27,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207585,2015-01-18,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
208866,2015-10-08,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
211319,2015-12-06,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
211617,2015-12-13,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
211823,2015-12-20,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,

In [20]:
avg_ru_Yds_list = []
avg_ru_Yds_list.append(5)
list(avg_ru_Yds_list)

[5]

In [21]:
#list(perfdf.columns.values)

In [ ]:
print(datetime.datetime.now())
# avg_ru_Yds_list = []
player = ''
year = 0
date = ''

avg_p_Cmp_list = []
avg_p_Att_list = []
avg_p_Yds_list = []
avg_p_TD_list = []
avg_Int_list = []
avg_Sk_list = []
avg_Yds_lost_list = []
avg_p_Lng_list = []
avg_p_Rate_list = []
avg_ru_Att_list = []
avg_ru_Yds_list = []
avg_ru_TD_list = []
avg_ru_Lng_list = []
avg_re_targ_list = []
avg_Rec_list = []
avg_re_Yds_list = []
avg_re_TD_list = []
avg_re_Lng_list = []
avg_fmb_list = []
avg_fmb_loss_list = []

for e,a in testdf.iterrows():
    #print(player,date, a[4])
    if player == a[2] and year == a[1]:
        ##general variables
        player = a[2]
        date = a[0]
        year = a[1]
        
        ##Assign new score for this season and player to find average
        avg_p_Cmp_list.append(a[4])
        avg_p_Att_list.append(a[5])
        avg_p_Yds_list.append(a[6])
        avg_p_TD_list.append(a[7])
        avg_Int_list.append(a[8])
        avg_Sk_list.append(a[9])
        avg_Yds_lost_list.append(a[10])
        avg_p_Lng_list.append(a[11])
        avg_p_Rate_list.append(a[12])
        avg_ru_Att_list.append(a[13])
        avg_ru_Yds_list.append(a[14])
        avg_ru_TD_list.append(a[15])
        avg_ru_Lng_list.append(a[16])
        avg_re_targ_list.append(a[17])
        avg_Rec_list.append(a[18])
        avg_re_Yds_list.append(a[19])
        avg_re_TD_list.append(a[20])
        avg_re_Lng_list.append(a[21])
        avg_fmb_list.append(a[22])
        avg_fmb_loss_list.append(a[23])



        ##Get Average Scores from lists
        avg_p_Cmp = Average(avg_p_Cmp_list)
        avg_p_Att = Average(avg_p_Att_list)
        avg_p_Yds = Average(avg_p_Yds_list)
        avg_p_TD = Average(avg_p_TD_list)
        avg_Int = Average(avg_Int_list)
        avg_Sk = Average(avg_Sk_list)
        avg_Yds_lost = Average(avg_Yds_lost_list)
        avg_p_Lng = Average(avg_p_Lng_list)
        avg_p_Rate = Average(avg_p_Rate_list)
        avg_ru_Att = Average(avg_ru_Att_list)
        avg_ru_Yds = Average(avg_ru_Yds_list)
        avg_ru_TD = Average(avg_ru_TD_list)
        avg_ru_Lng = Average(avg_ru_Lng_list)
        avg_re_targ = Average(avg_re_targ_list)
        avg_Rec = Average(avg_Rec_list)
        avg_re_Yds = Average(avg_re_Yds_list)
        avg_re_TD = Average(avg_re_TD_list)
        avg_re_Lng = Average(avg_re_Lng_list)
        avg_fmb = Average(avg_fmb_list)
        avg_fmb_loss = Average(avg_fmb_loss_list)
        
        
        ##Assign values to column
        testdf['avg_p_Cmp'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_p_Cmp
        testdf['avg_p_Att'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_p_Att
        testdf['avg_p_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_p_Yds
        testdf['avg_p_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_p_TD
        testdf['avg_Int'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_Int
        testdf['avg_Sk'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_Sk
        testdf['avg_Yds_lost'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_Yds_lost
        testdf['avg_p_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_p_Lng
        testdf['avg_p_Rate'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_p_Rate
        testdf['avg_ru_Att'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_ru_Att
        testdf['avg_ru_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_ru_Yds
        testdf['avg_ru_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_ru_TD
        testdf['avg_ru_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_ru_Lng
        testdf['avg_re_targ'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_re_targ
        testdf['avg_Rec'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_Rec
        testdf['avg_re_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_re_Yds
        testdf['avg_re_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_re_TD
        testdf['avg_re_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_re_Lng
        testdf['avg_fmb'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_fmb
        testdf['avg_fmb_loss'][(testdf['Player'] == player) & (testdf['Date'] == date)] = avg_fmb_loss
        
        ##Add in last week's metrics
        testdf['last_p_Cmp'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_p_Cmp
        testdf['last_p_Att'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_p_Att
        testdf['last_p_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_p_Yds
        testdf['last_p_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_p_TD
        testdf['last_Int'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_Int 
        testdf['last_Sk'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_Sk 
        testdf['last_Yds_lost'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_Yds_lost
        testdf['last_p_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_p_Lng
        testdf['last_p_Rate'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_p_Rate
        testdf['last_ru_Att'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_ru_Att
        testdf['last_ru_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_ru_Yds
        testdf['last_ru_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_ru_TD
        testdf['last_ru_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_ru_Lng
        testdf['last_re_targ'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_re_targ
        testdf['last_Rec'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_Rec
        testdf['last_re_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_re_Yds
        testdf['last_re_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_re_TD
        testdf['last_re_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_re_Lng
        testdf['last_fmb'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_fmb
        testdf['last_fmb_loss'][(testdf['Player'] == player) & (testdf['Date'] == date)] = last_fmb_loss
        
        
    else:
        avg_p_Cmp_list = [a[4]]
        avg_p_Att_list = [a[5]]
        avg_p_Yds_list = [a[6]]
        avg_p_TD_list = [a[7]]
        avg_Int_list = [a[8]]
        avg_Sk_list = [a[9]]
        avg_Yds_lost_list = [a[10]]
        avg_p_Lng_list = [a[11]]
        avg_p_Rate_list = [a[12]]
        avg_ru_Att_list = [a[13]]
        avg_ru_Yds_list = [a[14]]
        avg_ru_TD_list = [a[15]]
        avg_ru_Lng_list = [a[16]]
        avg_re_targ_list = [a[17]]
        avg_Rec_list = [a[18]]
        avg_re_Yds_list = [a[19]]
        avg_re_TD_list = [a[20]]
        avg_re_Lng_list = [a[21]]
        avg_fmb_list = [a[22]]
        avg_fmb_loss_list = [a[23]]
        
        ##Assign values to column
        testdf['avg_p_Cmp'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_p_Att'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_p_Yds'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_p_TD'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_Int'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_Sk'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_Yds_lost'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_p_Lng'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_p_Rate'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_ru_Att'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_ru_Yds'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_ru_TD'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_ru_Lng'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_re_targ'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_Rec'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_re_Yds'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_re_TD'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_re_Lng'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_fmb'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0
        testdf['avg_fmb_loss'][(perfdf['Player'] == player) & (perfdf['Date'] == date)] = 0

        testdf['last_p_Cmp'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_p_Att'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_p_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_p_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_Int'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0 
        testdf['last_Sk'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0 
        testdf['last_Yds_lost'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_p_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_p_Rate'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_ru_Att'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_ru_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_ru_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_ru_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_re_targ'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_Rec'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_re_Yds'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_re_TD'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_re_Lng'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_fmb'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        testdf['last_fmb_loss'][(testdf['Player'] == player) & (testdf['Date'] == date)] = 0
        
        
    ## Get this week's points to be added to the last week category of points
    last_p_Cmp = a[4]
    last_p_Att = a[5]
    last_p_Yds = a[6]
    last_p_TD = a[7]
    last_Int = a[8]
    last_Sk = a[9]
    last_Yds_lost = a[10]
    last_p_Lng = a[11]
    last_p_Rate = a[12]
    last_ru_Att = a[13]
    last_ru_Yds = a[14]
    last_ru_TD = a[15]
    last_ru_Lng = a[16]
    last_re_targ = a[17]
    last_Rec = a[18]
    last_re_Yds = a[19]
    last_re_TD = a[20]
    last_re_Lng = a[21]
    last_fmb = a[22]
    last_fmb_loss = a[23]
    player = a[2]
    date = a[0]
    year = a[1]
print(datetime.datetime.now())

In [73]:
testdf['avg_re_Yds'][(testdf['Player']=='Aaron Thomas') & (testdf['Date']== '1966-09-25')]

566    36
Name: avg_re_Yds, dtype: object

In [14]:
testdf

,Date,Year,Player,Tm,p_Cmp,p_Att,p_Yds,p_TD,Int,Sk,...,last_ru_Yds,last_ru_TD,last_ru_Lng,last_re_targ,last_Rec,last_re_Yds,last_re_TD,last_re_Lng,last_fmb,last_fmb_loss
109802,1995-11-27,1995,'Omar Ellison,San Diego Chargers,0.0,0.0,0.0,0.0,0.0,NaN,...,0,0,0,0,0,0,0,0,0,0
112421,1996-09-29,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,
112609,1996-10-06,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2,0,0,0,0,NaN,NaN
113230,1996-10-21,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,NaN,NaN
113449,1996-10-27,1996,'Omar Ellison,San Diego Chargers,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207585,2015-01-18,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
208866,2015-10-08,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
211319,2015-12-06,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
211617,2015-12-13,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,
211823,2015-12-20,2015,Zurlon Tipton,Indianapolis Colts,0.0,0.0,0.0,0.0,0.0,0.0,...,,,,,,,,,,

In [15]:
testdf.to_csv('test.csv')